version: "3"
services:
  master:
    build: ./master
    command: postgres -c ssl=on -c ssl_cert_file=/ssl/server.crt -c ssl_key_file=/ssl/server.key
    networks:
      - db
    ports:
      - "5500:5432"
  replica:
    build: ./replica
    command: /setup.sh
    networks:
      - db
    ports:
      - "5501:5432"
    depends_on:
      - master
networks:
  db:
