version: "3"
services:
  master:
    build: ./master
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    networks:
      - db
    ports:
      - "5500:5432"
  replica:
    build: ./replica
    command: /start_replication.sh
    networks:
      - db
    ports:
      - "5501:5432"
    depends_on:
      - master
networks:
  db:
