version: "3"
services:
  master:
    build: ./master
    networks:
      - db
    ports:
      - "5500:5432"
  replica:
    build: ./replica
    command: /setup.sh
    networks:
      - db
    ports:
      - "5501:5432"
    depends_on:
      - master
networks:
  db:
