version: "3"
services:
  master:
    build: ./master
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    networks:
      - db
    ports:
      - "5500:5432"
    environment:
      - REP_USER=rep_user
      - REP_PASSWORD=rep_password
  replica:
    build: ./replica
    command: /start_replication.sh
    networks:
      - db
    ports:
      - "5501:5432"
    depends_on:
      - master
    environment:
      - PGUSER=rep_user
      - PGPASSWORD=rep_password
      - PGAPPNAME=rep_test
      - PGSSLMODE=require
      - REP_SLOT=rep_test
networks:
  db:
